### PR TITLE
Split Glue File & Prepare for Sf 17

### PR DESCRIPTION
**Pull request by Disservin**
this splits the glue file into individual source files, should make it easier to persist backwards compatibility when trying to add support for a new version

lmk what you think (should have the same behaviour but didn't test it)

### CODE REVIEW

**Comment by Disservin** [comment]
i've also prepped a little sf 17 branch which at least builds but again not sure if it will run fine, see

https://github.com/Disservin/lila-stockfish-web/compare/split-glue-file...Disservin:lila-stockfish-web:split-glue-file-sf17

something I'm also not quite sure about is if our newly added numa code will be problematic/has to skipped/disabled, see

https://github.com/Sopel97/Stockfish/commit/a169c78b6d3b082068deb49a39aaa1fd75464c7f

**Comment by Disservin** [comment]
fyi stockfish 17 to be released soon

https://github.com/official-stockfish/Stockfish/pull/5566

**Comment by schlawg** [comment]
Apologies for the delay, nobody had contributed to this repo before so I wasn't watching it.

These changes work for me. Thanks! I'm curious if there's been any discussion about an official stockfish wasm?

**Comment by Disservin** [comment]
No worries ;)

> I'm curious if there's been any discussion about an official stockfish wasm?

There's no ongoing discussion nor can I recall that there was one in the past.

**Pull request merged**
