### PR TITLE
fix emscript version message

### PR DESCRIPTION
**Pull request by Disservin**

### CODE REVIEW

**Comment by niklasf** [comment]
Oops. Thanks!

**Comment by Disservin** [comment]
btw is there a way I can easily test the wasm build in this repo? I thought maybe by using the `wasm-cli.js` but that gives me
```
      var a = new Worker(new URL("sf17-79.js", import.meta.url), {
              ^

ReferenceError: Worker is not defined
```

**Comment by niklasf** [comment]
Make sure to build for nodejs instead of the default browser build:
```sh
./build.py clean
./build.py --node # !!!
node src/wasm-cli.js
```

**Comment by Disservin** [comment]
@niklasf what bench do you get for Stockfish? Using your commands I get `637095`,
the official stockfish bench that sf17 however has is `1484730`.

**Comment by Disservin** [comment]
Ah great, got me slightly worried for a sec there 👍

**Pull request merged**
